"""Add longitude and latitude to parking_sessions

Revision ID: 86041de9befc
Revises: 85b89fa95f39
Create Date: 2025-07-17 11:21:10.641442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86041de9befc'
down_revision: Union[str, Sequence[str], None] = '85b89fa95f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_sessions', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('parking_sessions', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_sessions', 'latitude')
    op.drop_column('parking_sessions', 'longitude')
    # ### end Alembic commands ###
