CARS_AVAILABLE = {
  "Acura": ["MDX", "RDX", "TLX", "Integra", "ZDX"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
  "Aston Martin": ["DB12", "DBX", "Vantage", "DBS"],
  "Audi": ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron", "e-tron GT", "RS3", "RS4", "RS5", "RS6", "RS7", "RS Q8", "S3", "S4", "S5", "S6", "S7", "S8", "SQ5", "SQ7", "SQ8", "TT"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur"],
  "BMW": ["2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "8 Series", "i4", "i5", "i7", "iX", "iX1", "iX2", "iX3", "M2", "M3", "M4", "M5", "M8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z4"],
  "Bugatti": ["Chiron", "Bolide", "Mistral"],
  "Buick": ["Enclave", "Encore GX", "Envision", "Envista"],
  "BYD": ["Atto 3", "Dolphin", "Han", "Seal", "Tang"],
  "Cadillac": ["CT4", "CT4-V", "CT4-V Blackwing", "CT5", "CT5-V", "CT5-V Blackwing", "Escalade", "Escalade ESV", "Escalade-V", "Lyriq", "XT4", "XT5", "XT6"],
  "Chevrolet": ["Blazer", "Blazer EV", "Bolt EUV", "Camaro", "Colorado", "Corvette", "Corvette E-Ray", "Corvette Z06", "Equinox", "Equinox EV", "Express", "Malibu", "Silverado 1500", "Silverado 2500HD", "Silverado 3500HD", "Silverado EV", "Suburban", "Tahoe", "Trailblazer", "Traverse", "Trax"],
  "Chrysler": ["Pacifica", "Pacifica Hybrid"],
  "Dodge": ["Charger", "Charger Daytona", "Durango", "Hornet"],
  "Ferrari": ["296 GTB", "296 GTS", "812 GTS", "F8 Tributo", "Portofino M", "Purosangue", "Roma", "SF90 Stradale", "SF90 Spider"],
  "Fiat": ["500e", "500X"],
  "Fisker": ["Ocean"],
  "Ford": ["Bronco", "Bronco Sport", "E-Transit", "Edge", "Escape", "Expedition", "Explorer", "F-150", "F-150 Lightning", "F-250 Super Duty", "F-350 Super Duty", "F-450 Super Duty", "Maverick", "Mustang", "Mustang GTD", "Mustang Mach-E", "Ranger", "Transit", "Transit Connect"],
  "Genesis": ["Electrified G80", "Electrified GV70", "G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "GMC": ["Acadia", "Canyon", "Hummer EV", "Hummer EV SUV", "Sierra 1500", "Sierra 2500HD", "Sierra 3500HD", "Terrain", "Yukon", "Yukon XL"],
  "Honda": ["Accord", "Accord Hybrid", "Civic", "Civic Hatchback", "Civic Hybrid", "Civic Si", "Civic Type R", "CR-V", "CR-V Hybrid", "HR-V", "Odyssey", "Passport", "Pilot", "Prologue", "Ridgeline"],
  "Hyundai": ["Avante", "Avante Hybrid", "Avante N", "Ioniq 5", "Ioniq 6", "Kona", "Kona Electric", "Kona N", "Nexo", "Palisade", "Santa Cruz", "Santa Fe", "Santa Fe Hybrid", "Sonata", "Sonata Hybrid", "Tucson", "Tucson Hybrid", "Tucson Plug-in Hybrid", "Venue"],
  "Infiniti": ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF"],
  "Jeep": ["Cherokee", "Compass", "Gladiator", "Grand Cherokee", "Grand Cherokee 4xe", "Grand Cherokee L", "Grand Wagoneer", "Wagoneer", "Wrangler", "Wrangler 4xe"],
  "Kia": ["Carnival", "EV6", "EV9", "Forte", "K5", "Niro", "Niro EV", "Niro Hybrid", "Niro Plug-in Hybrid", "Rio", "Seltos", "Sorento", "Sorento Hybrid", "Sorento Plug-in Hybrid", "Soul", "Sportage", "Sportage Hybrid", "Sportage Plug-in Hybrid", "Stinger", "Telluride"],
  "Lamborghini": ["Aventador", "Huracan", "Revuelto", "Urus"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Lexus": ["ES", "ES Hybrid", "GX", "IS", "LC", "LC Hybrid", "LS", "LS Hybrid", "LX", "NX", "NX Hybrid", "NX Plug-in Hybrid", "RC", "RX", "RX Hybrid", "RZ", "TX", "UX", "UX Hybrid"],
  "Lincoln": ["Aviator", "Corsair", "Nautilus", "Navigator", "Navigator L"],
  "Lotus": ["Eletre", "Emira", "Evija"],
  "Lucid": ["Air", "Air Grand Touring", "Air Pure", "Air Sapphire", "Air Touring", "Gravity"],
  "Maserati": ["Ghibli", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  "Mazda": ["CX-30", "CX-5", "CX-50", "CX-70", "CX-90", "CX-90 PHEV", "Mazda3", "Mazda3 Hatchback", "MX-5 Miata", "MX-30"],
  "McLaren": ["720S", "750S", "765LT", "Artura", "GT"],
  "Mercedes-Benz": ["A-Class", "AMG GT", "C-Class", "CLA", "CLE", "E-Class", "EQB", "EQE", "EQE SUV", "EQS", "EQS SUV", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "Maybach S-Class", "S-Class", "SL"],
  "Mini": ["Clubman", "Convertible", "Cooper", "Cooper S", "Countryman", "John Cooper Works"],
  "Mitsubishi": ["Eclipse Cross", "Mirage", "Mirage G4", "Outlander", "Outlander PHEV", "Outlander Sport"],
  "Nissan": ["Altima", "Ariya", "Armada", "Frontier", "GT-R", "Kicks", "Leaf", "Maxima", "Murano", "Pathfinder", "Rogue", "Rogue Sport", "Sentra", "Titan", "Versa", "Z"],
  "Polestar": ["Polestar 2", "Polestar 3", "Polestar 4"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Cayenne Coupe", "Macan", "Panamera", "Taycan", "Taycan Cross Turismo"],
  "Ram": ["1500", "1500 Classic", "2500", "3500", "ProMaster", "ProMaster City"],
  "Renault": ["Arkana", "Austral", "Captur", "Clio", "Duster", "Espace", "Grand Koleos", "Kadjar", "Kangoo", "Kardian", "Kiger", "Koleos", "Kwid", "Master", "Megane", "Megane E-Tech", "Oroch", "Rafale", "Sandero", "Scenic", "Symbioz", "Talisman", "Trafic", "Triber", "Twingo", "Twizy", "Zoe"],
  "Rivian": ["R1S", "R1T", "R2", "R3"],
  "Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Spectre", "Wraith"],
  "Subaru": ["Ascent", "BRZ", "Crosstrek", "Crosstrek Hybrid", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "WRX"],
  "Tesla": ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
  "Toyota": ["4Runner", "4Runner i-FORCE MAX", "Avalon", "bZ4X", "Camry", "Camry Hybrid", "C-HR", "Corolla", "Corolla Cross", "Corolla Cross Hybrid", "Corolla Hatchback", "Corolla Hybrid", "Crown", "Crown Signia", "GR Corolla", "GR Supra", "GR86", "Grand Highlander", "Grand Highlander Hybrid", "Highlander", "Highlander Hybrid", "Land Cruiser", "Mirai", "Prius", "Prius Plug-in Hybrid", "RAV4", "RAV4 Hybrid", "RAV4 Prime", "Sequoia", "Sienna", "Tacoma", "Tundra", "Tundra Hybrid", "Venza"],
  "Volkswagen": ["Arteon", "Atlas", "Atlas Cross Sport", "Golf GTI", "Golf R", "ID.4", "ID.Buzz", "Jetta", "Jetta GLI", "Taos", "Tiguan"],
  "Volvo": ["C40 Recharge", "S60", "S60 Recharge", "S90", "S90 Recharge", "V60", "V60 Cross Country", "V90", "V90 Cross Country", "XC40", "XC40 Recharge", "XC60", "XC60 Recharge", "XC90", "XC90 Recharge"],
  "VinFast": ["VF 6", "VF 7", "VF 8", "VF 9"]
}